stages:
  - build

build:
  stage: build
  image: python:3.7-slim
  script:
    - apt-get update && apt-get install -y make
    - make deps
    - make deps-test
    - make lint
    - make coverage
  artifacts:
    reports:
      cobertura: code/python/.coverage.xml
