stages:
  - build

include:
  - template: Jobs/Build.gitlab-ci.yml

build:
  # dind: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:v1.0.0"
  # kaniko: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image/kaniko:stable"
  image: "$BUILD_IMAGE"
