stages:
  - build

include:
  - template: Jobs/Build.gitlab-ci.yml

variables:
  DOCKERFILE_PATH: "code/docker/ci/Dockerfile.python"

build:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image/kaniko:stable"
