version: '2.3'

services:

  python:
    build:
      context: ../../../
      dockerfile: code/docker/devel/Dockerfile.python
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
        - ../../../:/home/slub/workspace:Z
        - ../../../data/runtime/container/python/.bash_history:/home/slub/.bash_history:Z

  annif:
    build:
      context: .
      dockerfile: Dockerfile.annif
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "127.0.0.1:5000:5000/tcp" # annif development server
    volumes:
      - ../../../data/runtime/container/annif:/annif-projects:Z
      - ../../../data/resources/annif-corpora:/annif-corpora:Z
      - ../../../data/runtime/cache:/docsa-cache:Z

