version: '2.3'

services:

  python:
    build:
      context: ../../../
      dockerfile: code/docker/devel/Dockerfile.python
      args:
        # UID: ${UID:-1000}
        # GID: ${GID:-1000}
        BASE_IMAGE: ${BASE_IMAGE}
    ports:
      - "0.0.0.0:5000:5000/tcp" # slub-docsa rest development server
    security_opt:
      - label=disable
    volumes:
        - ../../../:/home/slub/workspace:z
        - ../../../data/runtime/container/python/.bash_history:/home/slub/.bash_history:z

  annif:
    build:
      context: .
      dockerfile: Dockerfile.annif
      # args:
        # UID: ${UID:-1000}
        # GID: ${GID:-1000}
    ports:
      - "0.0.0.0:5001:5000/tcp" # annif development server
    volumes:
      - ../../../data/runtime/container/annif:/annif-projects:z
      - ../../../data/resources/annif-corpora:/annif-corpora:z
      - ../../../data/runtime/cache:/docsa-cache:z

